name: btk_todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
    
dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
